---
# vars file for install-bareos-client

#####     Required Variables      #####
# Fill in appropriate values below unless passing from a higher precedence

# The hostname of the machine you are backing up
client_hostname: "{{  hostvars[inventory_hostname]['ansible_hostname']  }}"

# The fully qualified domain name or IP address of the machine you are adding to be backed up
client_fqdn: "{{  hostvars[inventory_hostname]['ansible_default_ipv4']['address']  }}"
# The fully qualified domain name or IP address of where your Bareos Storage Daemon/Service is running. For most people this will probably be the same FQDN of where the Bareos Director daemon/service runs (your Bareos Server), but can be a separate machine.
bareos_storage_daemon_fqdn: "10.0.55.249"

# It needs to match the client_password entered when adding the bareos client program to the machine you want to backup. The value for this is usually a very long string (47 characters) of random characters.
client_password: "client_password"

# The storage dmeadirector password variable is the bareos-dir password found on your Bareos Server
storage_director_password: "{{ lookup('env', 'storage_password') }}"

# Backup Level - Full, Incremental, Differential
level: Full

# Permits you to control the order in which your jobs will be run. The higher the number, the lower the job priority. 
priority: 6

# See the README documentation for more detailed info on these variables
backup_schedule:
  - Run = Full daily at 02:00


filesets_to_backup:
  - File = "/tmp/backup.sql"
filesets_to_exclude:
  - File = "/var/www/html/.github"
  - File = "/var/www/html/.git"
  - File = "/var/www/html/.gitignore"



